<a href="https://colab.research.google.com/github/psg-dsci/nurds/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)


In [ ]:
my_range_array = np.arange(1, 10, 2)


In [ ]:
lin_space_array = np.linspace(0, 10, 5)  # 5 equally spaced points from 0 to 10
print(lin_space_array)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
identity_matrix = np.eye(3)  # 3x3 identity matrix
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_uniform_array = np.random.rand(2, 2)  # 2x2 array of random numbers between 0 and 1
print(random_uniform_array)


[[0.38067268 0.61772073]
 [0.59855731 0.5589222 ]]


In [ ]:
random_normal_array = np.random.randn(3, 3)  # 3x3 array of random numbers from a normal distribution
print(random_normal_array)


[[ 0.30687809  0.08516492 -1.1823436 ]
 [ 0.90060654  1.6999505  -0.5636604 ]
 [-0.7877466   1.10537342 -0.41537362]]


In [ ]:
arr = np.arange(1, 10)
reshaped_array = arr.reshape((3, 3))  # Reshaping arr to a 3x3 array
print(reshaped_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.array([1, 3, 5, 7, 9])
print(np.max(arr))  # Output: 9
print(np.min(arr))  # Output: 1


9
1


In [ ]:
arr = np.array([1, 3, 5, 7, 9])
print(np.argmax(arr))  # Output: 4 (index of the maximum element)
print(np.argmin(arr))  # Output: 0 (index of the minimum element)


4
0


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice_array = arr[:2, 1:]
print(slice_array)


[[2 3]
 [5 6]]


In [ ]:
arr = np.array([1, 2, 3])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))


[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
